### ISSUE TITLE
end of section 1.3 exercise instructions not clear

### ISSUE THREAD

**Issue by gamecubate** [AgileArtificialIntelligence/AgileArtificialIntelligence.github.io#1]
At the end of section exercise, you state ```Create a new test, called testSmallExample, that tests that feeding our perceptron p with different values (e.g., -2 and 2 gives 0 as result)```.

It is not clear what you mean for the user to do.

Should the method be given a values parameter, in which case it should be named testSmallExample:?

Or should it instead be the body of the original testSmallExample method that should be augmented with additional sub-tests, e.g.,
```
testSmallExample
	| p result |
	p := Neuron new.
	p weights: #(1 2).
	p bias: -2.

	result := p feed: #(5 2).
	self assert: result equals: 1.

	result := p feed: #(-2 2)
	self assert: result equals: 0.
```
?

**Comment by bergel** [comment]
Indeed, I meant "it instead be the body of the original testSmallExample method that should be augmented with additional sub-tests". 
Thanks!
The chapter is updated accordingly.
